language: swift

osx_image: xcode13.1

script:
  - xcodebuild -scheme GithubAwesomeRepos -workspace GithubAwesomeRepos.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=13.1' build test
  #- sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
